import time
import random
from urllib.parse import urlparse, parse_qs, urlencode, urlunparse
from playwright.sync_api import sync_playwright
import requests

import os

TELEGRAM_BOT_TOKEN = os.environ["TELEGRAM_BOT_TOKEN"]
TELEGRAM_CHAT_ID = os.environ["TELEGRAM_CHAT_ID"]


def send_telegram_message(message):
    url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"

    response = requests.post(
        url,
        json={
            "chat_id": TELEGRAM_CHAT_ID,
            "text": message,
        },
        timeout=30,
    )

    if not response.ok:
        print("Telegram error:")
        print(response.text)
        print("Message length:", len(message))

    response.raise_for_status()

BASE_URL = (
    "https://www.lazada.sg/pokemon-store-online-singapore/"
    "?q=All-Products&shop_category_ids=762252&from=wangpu"
)

PAGE_SIZE = 40

# Realistic Chrome build to keep the UA and sec-ch-ua headers consistent.
CHROME_VERSION = "124.0.0.0"

USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    f"Chrome/{CHROME_VERSION} Safari/537.36"
)

# Small pool of realistic viewport sizes; picked randomly per run
# instead of using a single fixed 1920x1080 every time.
VIEWPORTS = [
    {"width": 1920, "height": 1080},
    {"width": 1536, "height": 864},
    {"width": 1440, "height": 900},
    {"width": 1366, "height": 768},
]

# Injected before any page script runs, to patch over the most common
# automation tells that bot-detection scripts check for.
STEALTH_INIT_SCRIPT = """
// Hide the webdriver flag
Object.defineProperty(navigator, 'webdriver', {
    get: () => undefined
});

// Pretend a normal plugin list exists (headless Chromium reports none)
Object.defineProperty(navigator, 'plugins', {
    get: () => [1, 2, 3, 4, 5]
});

// Normal language list
Object.defineProperty(navigator, 'languages', {
    get: () => ['en-SG', 'en-US', 'en']
});

// window.chrome exists on real Chrome, not on headless by default
window.chrome = { runtime: {} };

// Spoof a plausible permissions response for notifications
const originalQuery = window.navigator.permissions.query;
window.navigator.permissions.query = (parameters) => (
    parameters.name === 'notifications'
        ? Promise.resolve({ state: Notification.permission })
        : originalQuery(parameters)
);
"""


def build_page_url(base_url: str, page_num: int) -> str:
    parsed = urlparse(base_url)
    query = parse_qs(parsed.query)

    query["page"] = [str(page_num)]
    query["style"] = ["list"]

    return urlunparse(
        parsed._replace(query=urlencode(query, doseq=True))
    )


def human_pause(min_s=1.5, max_s=4.0):
    """Random delay to avoid perfectly uniform, machine-speed timing."""
    time.sleep(random.uniform(min_s, max_s))


def scrape_page(page, url: str):
    """
    Loads the normal Lazada page and captures the AJAX product
    data generated by that page.

    Stock is taken from Lazada's `inStock` field.
    """

    captured = {}

    def on_response(response):
        # Only inspect Lazada AJAX responses
        if "ajax=true" not in response.url:
            return

        if "lazada.sg" not in response.url:
            return

        try:
            if response.status != 200:
                return

            data = response.json()

            items = data.get("mods", {}).get("listItems")

            if items is not None:
                captured["items"] = items

        except Exception:
            pass

    page.on("response", on_response)

    try:
        # IMPORTANT:
        # Load the normal storefront page, NOT the AJAX URL directly.
        page.goto(
            url,
            wait_until="domcontentloaded",
            timeout=45000
        )
    except Exception:
        print("  Warning: page took too long to load, continuing...")

    # Give Lazada's normal page requests time to finish, with some
    # jitter instead of a fixed wait every single time.
    page.wait_for_timeout(random.randint(4000, 7000))

    # Small human-like scroll, some detection scripts check for any
    # interaction/movement at all before trusting a session.
    try:
        page.mouse.wheel(0, random.randint(200, 800))
        page.wait_for_timeout(random.randint(300, 900))
    except Exception:
        pass

    page.remove_listener("response", on_response)

    items = captured.get("items", [])

    if not items:
        print("  No product AJAX data captured.")

    return items


def scrape_all_pages(page, max_pages=3):
    """
    Scrapes pages sequentially.

    Stops when:
    - A page has fewer than 40 products
    - A duplicate product is found
    - No products are returned
    """

    all_items = []
    seen_ids = set()

    for page_num in range(1, max_pages + 1):

        # Delay between pages, randomized instead of a flat 3s.
        if page_num > 1:
            print("  Waiting before next page...")
            human_pause(2.5, 5.5)

        url = build_page_url(BASE_URL, page_num)

        print(f"\nScraping page {page_num}...")
        items = scrape_page(page, url)

        print(f"  Found {len(items)} products")

        if not items:
            print("  No products found. Stopping.")
            break

        # Check whether this page contains products we've already seen.
        duplicate = any(
            item.get("itemId") in seen_ids
            for item in items
            if item.get("itemId")
        )

        if duplicate:
            print("  Duplicate product found. Stopping.")
            break

        # Add products
        for item in items:
            item_id = item.get("itemId")

            if not item_id or item_id in seen_ids:
                continue

            seen_ids.add(item_id)

            item_url = item.get("itemUrl", "")

            if item_url.startswith("//"):
                item_url = "https:" + item_url

            all_items.append({
                "itemId": item_id,
                "name": item.get("name"),
                "price": item.get("price"),
                "url": item_url,
                "inStock": item.get("inStock") is True,
            })

        print(f"  Total products: {len(all_items)}")

        # Fewer than 40 means we've reached the final page.
        if len(items) < PAGE_SIZE:
            print(
                f"  Page contains fewer than {PAGE_SIZE} products. "
                "Stopping."
            )
            break

    return all_items


def get_all_items(page):
    """
    Returns all products with name, price and URL.
    """

    items = scrape_all_pages(page)

    return [
        {
            "name": item["name"],
            "price": item["price"],
            "url": item["url"],
        }
        for item in items
    ]


def get_in_stock_items(page):
    """
    Returns only products where Lazada explicitly reports
    inStock == True.
    """

    items = scrape_all_pages(page)

    return [
        {
            "name": item["name"],
            "price": item["price"],
            "url": item["url"],
        }
        for item in items
        if item["inStock"]
    ]


if __name__ == "__main__":

    # Random startup delay
    startup_delay = random.uniform(5, 90)
    print(f"Startup delay: {startup_delay:.1f}s")
    time.sleep(startup_delay)

    with sync_playwright() as p:

        browser = p.chromium.launch(
            headless=True,
            args=[
                "--disable-blink-features=AutomationControlled",
            ],
        )

        viewport = random.choice(VIEWPORTS)

        context = browser.new_context(
            user_agent=USER_AGENT,
            viewport=viewport,
            locale="en-SG",
            timezone_id="Asia/Singapore",
            extra_http_headers={
                "Accept-Language": "en-SG,en-US;q=0.9,en;q=0.8",
                "sec-ch-ua": (
                    f'"Chromium";v="{CHROME_VERSION.split(".")[0]}", '
                    f'"Google Chrome";v="{CHROME_VERSION.split(".")[0]}", '
                    '"Not-A.Brand";v="99"'
                ),
                "sec-ch-ua-mobile": "?0",
                "sec-ch-ua-platform": '"Windows"',
            },
        )

        context.add_init_script(STEALTH_INIT_SCRIPT)

        page = context.new_page()

        # Small pause before the very first navigation.
        human_pause(1.0, 2.5)

        # Scrape everything once
        all_items = scrape_all_pages(page)

        browser.close()

    # -----------------------------
    # ALL ITEMS
    # -----------------------------

    print("\n=== ALL ITEMS ===")

    for item in all_items:
        print(
            f"{item['name']}\n"
            f"Price: ${item['price']}\n"
            f"Stock: {'IN STOCK' if item['inStock'] else 'OUT OF STOCK'}\n"
            f"URL: {item['url']}\n"
        )

    # -----------------------------
    # IN STOCK
    # -----------------------------

    in_stock_items = [
        item
        for item in all_items
        if item["inStock"]
    ]

    print("\n=== IN STOCK ITEMS ===")

    for item in in_stock_items:
        print(
            f"{item['name']}\n"
            f"${item['price']}\n"
            f"{item['url']}\n"
        )

    print(
        f"\nTotal: {len(all_items)} | "
        f"In stock: {len(in_stock_items)}"
    )

    if all_items is None or len(all_items) == 0:
        message = "🔴 Bot checked / no data captured."
    else:
        if in_stock_items:
            message = "🟢 Items currently in stock:\n\n"
            for item in in_stock_items:
                message += (
                    f"{item['name']}\n"
                    f"${item['price']}\n"
                    f"{item['url']}\n\n"
                )
        else:
            message = "🔴 No products currently in stock.\n\n"

    send_telegram_message(message)